### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by Tyrdall** [skoczen/django-ajax-uploader#17] opened 2012-01-08 19:21 UTC
The following issue is driven me crazy:

What I've done:
I customized the LocalUploadBackend and the AjaxFileUploader classes a bit, because of thumbnail stuff and so on.
Now I tried to write some tests, but after hours of debugging it still doesn't work.

What 've found out:
When I'm into debug and stop at the following code sample....:

success = backend.upload(upload, filename, is_raw)

...then calling request.POST in my debug I/O to check for the hexa stuff of the file (everything seems ok). In this case the whole test works and the file is uploaded.

When I'm not into debug mode and run the test without calling request.POST the following error appears:

AssertionError: Cannot read more than the available bytes from the HTTP incoming data.

Would be awesome if you can help me with that. Thanks!

**Comment by skoczen** [comment] 2012-01-09 01:36
Hey, 

Without seeing your code, there's nothing I can to do help. Also, the error you're describing indicates that it's somewhere in your debug code, not the upload code itself. Maybe that helps?

**Comment by Tyrdall** [comment] 2012-01-09 06:29
Thanks for the reply. I inherited almost everything from your code and just added some additional code, which doesn't really effect the base.

tests:
class AjaxUploadTestFork(BaseTestCase):

```
def setUp(self):  
    self.test_dir = os.path.dirname(__file__)
    test_file = open("%s/InstitutionImages/test.png" % settings.MEDIA_ROOT,
                     'rb')
    self.test_file_1 = test_file
    self.test_file_1_hash = hashlib.sha1(self.test_file_1.read())\
                                   .hexdigest()
    self.test_file_1.seek(0)

def tearDown(self):
    pass

def test_upload_raw_post_local_backend(self):
    file_data = self.test_file_1.read()
    response = self.client.post('%s?institution=1&qqfile=test.png' 
                                % reverse('ajax_upload'), file_data,
                                content_type='application/octet-stream',
                                HTTP_X_REQUESTED_WITH='XMLHttpRequest')
    uploaded_file_path = os.path.join(settings.MEDIA_ROOT, 'InstitutionImages',
                                      'test.png')
    uploaded_file = open(uploaded_file_path, 'rb')
    self.assertTrue(os.path.exists(uploaded_file_path))
    self.assertEquals(hashlib.sha1(uploaded_file.read()).hexdigest(),
                      self.test_file_1_hash)
```

views.py
class AjaxFileUploaderFork(AjaxFileUploader):

```
def _ajax_upload(self, request):
    if request.method == "POST":
        if request.is_ajax():
            upload = request
            is_raw = True
            try:
                filename = request.GET['qqfile']
            except KeyError:
                return HttpResponseBadRequest("AJAX request not valid")
        else:
            is_raw = False
            if len(request.FILES) == 1:
                upload = request.FILES.values()[0]
            else:
                raise Http404("Bad Upload")
            filename = upload.name

        backend = self.get_backend()
        institution = get_institution_moderation(request)
        if not institution:
            orig_inst = Institution.objects.get(id=int(request.GET.get(
                'institution')))
            institution = add_moderation_class(orig_inst)
        backend.UPLOAD_DIR = 'InstitutionImages/%d' % institution.id

        filename, url = backend.setup(filename)
        success = backend.upload(upload, filename, is_raw)

        extra_context = backend.upload_complete(request, filename)
        photo = InstitutionPhoto()
        photo.image.save(filename, ImageFile(open(url, 'r')), save=True)
        photo.name = filename
        photo.save()
        institution.photos.add(photo)
        institution = set_moderation_status_pending(institution)
        thumbnail_options = dict(size=(100, 100), crop=True, bw=True,
                                 upscale=True)
        thumbnail = get_thumbnailer(photo.image).get_thumbnail(
            thumbnail_options)

        ret_json = {'success': success, 'filename': filename,
                    'thumbnail': thumbnail.url}
        if extra_context is not None:
            ret_json.update(extra_context)

        return HttpResponse(json.dumps(ret_json))
```

**Comment by Tyrdall** [comment] 2012-01-09 13:05
Now, I've tried running your delivered tests and the same error appears:

```
AssertionError: Cannot read more than the available bytes from the HTTP incoming data.
Datei "/home/tobi/Projects/academic/src/webapps/django/project/manage.py", Zeile 14, in <module>
  execute_manager(settings)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/core/management/__init__.py", Zeile 438, in execute_manager
  utility.execute()
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/core/management/__init__.py", Zeile 379, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/core/management/base.py", Zeile 191, in run_from_argv
  self.execute(*args, **options.__dict__)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/core/management/base.py", Zeile 220, in execute
 output = self.handle(*args, **options)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/south/management/commands/test.py", Zeile 8, in handle
  super(Command, self).handle(*args, **kwargs)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/core/management/commands/test.py", Zeile 37, in handle
  failures = test_runner.run_tests(test_labels)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/simple.py", Zeile 360, in run_tests
  result = self.run_suite(suite)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/simple.py", Zeile 316, in run_suite
  return unittest.TextTestRunner(verbosity=self.verbosity, failfast=self.failfast).run(suite)
Datei "/usr/lib/python2.7/unittest/runner.py", Zeile 151, in run
  test(result)
Datei "/usr/lib/python2.7/unittest/suite.py", Zeile 70, in __call__
  return self.run(*args, **kwds)
 Datei "/usr/lib/python2.7/unittest/suite.py", Zeile 108, in run
  test(result)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/testcases.py", Zeile 299, in __call__
  super(TransactionTestCase, self).__call__(result)
 Datei "/usr/lib/python2.7/unittest/case.py", Zeile 391, in __call__
  return self.run(*args, **kwds)
Datei "/usr/lib/python2.7/unittest/case.py", Zeile 327, in run
  testMethod()
Datei "/home/tobi/Envs/academic/src/ajaxuploader/ajaxuploader/tests/default_storage_backend.py", Zeile 51, in test_upload_raw_post_local_backend
  HTTP_X_REQUESTED_WITH='XMLHttpRequest')
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/client.py", Zeile 449, in post
  response = super(Client, self).post(path, data=data, content_type=content_type, **extra)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/client.py", Zeile 259, in post
  return self.request(**r)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/client.py", Zeile 381, in request
  response = self.handler(environ)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/client.py", Zeile 84, in __call__
  response = self.get_response(request)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/core/handlers/base.py", Zeile 111, in get_response
  response = callback(request, *callback_args, **callback_kwargs)
Datei "/home/tobi/Envs/academic/src/ajaxuploader/ajaxuploader/views.py", Zeile 15, in __call__
  return self._ajax_upload(request)
Datei "/home/tobi/Envs/academic/src/ajaxuploader/ajaxuploader/views.py", Zeile 53, in _ajax_upload
  success = backend.upload(upload, filename, is_raw)
Datei "/home/tobi/Envs/academic/src/ajaxuploader/ajaxuploader/backends/base.py", Zeile 27, in upload
  chunk = uploaded.read(self.BUFFER_SIZE)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/http/__init__.py", Zeile 301, in read
  return self._stream.read(*args, **kwargs)
Datei "/home/tobi/Envs/academic/lib/python2.7/site-packages/django/test/client.py", Zeile 51, in read
  assert self.__len >= num_bytes, "Cannot read more than the available bytes from the HTTP incoming data."
```

**Comment by skoczen** [comment] 2012-01-09 15:25
Thanks for the info.  This week looks pretty crazy for me, but I'll try to get to digging into it this weekend!

**Comment by fhahn** [comment] 2012-01-09 16:22
Hey!

I think the problem is a bug in Django <= 1.3.1 

Have a look at the following bug [1].

The bug is fixed in Django's trunk.

You can find information about the bug in [2]

Cheers,
Flo

[1] https://code.djangoproject.com/ticket/15785
[2] https://github.com/GoodCloud/django-ajax-uploader/blob/master/ajaxuploader/tests/default_storage_backend.py#L42

**Comment by skoczen** [comment] 2012-01-27 05:20
Hey Tyrdall, Fhahn's explanation seems to match what you're seeing - I'm going to close this up. Re-open if that's inaccurate!

**Closed as completed by skoczen** 2012-01-27 05:20 UTC
